# top level stuff you probably don't need to touch
#highlighter: pygments
highlighter: rouge
#markdown: rdiscount

markdown: "kramdown" # was: "redcarpet" # was: "kramdown"
kramdown:
  input: "GFM"
  syntax_highlighter: "coderay"
  coderay_line_numbers: nil
#rdiscount:
#  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
#port: 3000
safe: true
future: true
bloglength: 5


# edit here to achieve your personal greatness
url: https://kspviswa.github.io
baseurl: ""
title: kspviswa
author: kspviswa
description: My digital footprint in open-source family.
avatar: profile1.png
email: kspviswa.github@gmail.com
github: kspviswa
twitter: kspviswa
linkedin: kspviswa
stackoverflow: users/3315943/viswa-ksp   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: 
    shortname: kspviswa
# google_analytics: UA-78703019-1


# needed for travis-ci build
exclude: [vendor]
